### PR TITLE
Add adapt

### PR DESCRIPTION
**Pull request by bakkot**

### CODE REVIEW

**Comment by michaelficarra** [comment]
LGTM, but can't we call this `map` and swap the order of the parameters?

**Comment by bakkot** [comment]
Fixed the argument order.

Don't have strong opinions about the name, but `map` seems like kind of a weird choice - this operates on reducers, not trees. It's more like `compose`, if anything.

Was mostly just following what I did in [java](https://github.com/shapesecurity/shift-java/blob/d2ac3372c3cb2ba70c76df59028f2a887cabd6fb/src/main/java/com/shapesecurity/shift/es2016/reducer/WrappedReducer.java) earlier.

**Comment by michaelficarra** [comment]
This is definitely just `map`. Reducers are functors too.

**Review by michaelficarra — APPROVED** [review]
Good enough.

**Pull request merged**
