### PR TITLE
refactor to avoid babels attempt at transpiling to optimize for tail calls

### PR DESCRIPTION
**Pull request by jsoverson**
Addresses #19

### CODE REVIEW

**Comment by michaelficarra** [comment]
Ugh, this looks gross. Can't we just disable the tail call transformation in babel?

**Comment by jsoverson** [comment]
There wasn't an obvious [transform](https://babeljs.io/docs/plugins/#transform) plugin for it and didn't dig deeper into where it was implemented.

**Comment by michaelficarra** [comment]
That's babel 6.x documentation. We're using babel 5.x. There's probably something we can pass to `--blacklist`. Try `--blacklist es6.tailCall`.

**Comment by jsoverson** [comment]
That works, but turns out a chunk of the performance gain was due to simply removing the block from the default case, which apparently (when used with `let`) transpiles to an IIFE.

**Comment by michaelficarra** [comment]
Okay, then just send a PR removing the block.

**Comment by jsoverson** [comment]
Updated PR

**Pull request merged**
